version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres-icilocation
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    volumes:
      - ../app:/usr/src/app/app
      # - ../node_modules:/usr/src/app/node_modules
