version: '3.8'

services:
  app:
      build: .
      ports:
        - "3008:3008"
      environment:
        - DATABASE_URL=${DATABASE_URL}
      depends_on:
        - db
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres-icilocation
    restart: always
    environment:
      POSTGRES_PASSWORD: crampte
      POSTGRES_USER: admin
      POSTGRES_DB: icilocation
    ports:
        - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

# use 'docker compose up -d' to start the container

# docker run --name db -e POSTGRES_PASSWORD=crampte -e POSTGRES_USER=admin -e POSTGRES_DB=icilocation -p 5432:5432 -v ./postgres_data:/var/lib/postgresql/data -d postgis/postgis:16-3.4

# services:
#   db:
#     build: .
#     container_name: postgres-icilocation
#     restart: always
#     environment:
#       - POSTGRES_PASSWORD=crampte
#       - POSTGRES_USER=admin
#       - POSTGRES_DB=icilocation
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data
#   db_shadow:
#     build: .
#     container_name: postgres-icilocation-shadow
#     restart: always
#     environment:
#       - POSTGRES_PASSWORD=crampte
#       - POSTGRES_USER=admin
#       - POSTGRES_DB=icilocationshadow
#     ports:
#       - "5433:5432"
#     volumes:
#       - ./postgres_data_shadow:/var/lib/postgresql/data

# use 'docker-compose up --build' to start the container